version: 2.1
orbs:
  node: circleci/node@5.2.0
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
  deploy:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run: npm install --global surge
      - run: surge --project ./build --domain https://rewards-program-leszek-p.surge.sh
workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
